Repository Ocramius/ProxyManager, pull requests merged in 2019-12, with the labels that each got.

#522 Feature: integration with webimpress/safe-writer
  composer.json
  src/ProxyManager/Exception/FileNotWritableException.php
  src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php
  src/ProxyManager/GeneratorStrategy/FileWriterGeneratorStrategy.php
  tests/ProxyManagerTest/Exception/FileNotWritableExceptionTest.php
Labels: enhancement

#532 Stable PHP 7.4 builds - Travis CI config
  .travis.yml
Labels: dependencies, enhancement

#537 Use ReflectionClass to create proxied class instance inside PublicScopeSimulator
  src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php
  tests/ProxyManagerTest/ProxyGenerator/Util/PublicScopeSimulatorTest.php
  tests/language-feature-scripts/access-interceptor-scope-localizer-serialized-class-private-property-isset.phpt
  tests/language-feature-scripts/access-interceptor-scope-localizer-serialized-class-private-property-read.phpt
  tests/language-feature-scripts/access-interceptor-scope-localizer-serialized-class-private-property-unset.phpt
  tests/language-feature-scripts/access-interceptor-scope-localizer-serialized-class-private-property-write.phpt
  tests/language-feature-scripts/access-interceptor-scope-localizer-serialized-class-protected-property-isset.phpt
  tests/language-feature-scripts/access-interceptor-scope-localizer-serialized-class-protected-property-read.phpt
  tests/language-feature-scripts/access-interceptor-scope-localizer-serialized-class-protected-property-unset.phpt
  tests/language-feature-scripts/access-interceptor-scope-localizer-serialized-class-protected-property-write.phpt
Labels: bug
