Repository Ocramius/ProxyManager, pull requests merged in 2019-03, with the labels that each got.

#449 Remove big-header section from documentation
  doc-template/css/main.css
  doc-template/default.twig
Labels: docs, enhancement

#450 Removed unused badges from `README.md`
  README.md
Labels: enhancement

#452 Revert BC break - `: void` cannot be added as return type to open classes
  phpcs.xml.dist
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizerGenerator.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolderGenerator.php
  src/ProxyManager/ProxyGenerator/LazyLoadingGhostGenerator.php
  src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php
  src/ProxyManager/ProxyGenerator/ProxyGeneratorInterface.php
  src/ProxyManager/ProxyGenerator/RemoteObjectGenerator.php
  src/ProxyManager/Signature/SignatureCheckerInterface.php
Labels: bug
