Repository Ocramius/ProxyManager, pull requests merged in 2020-04, with the labels that each got.

#587 Fix test suite deprecations
  composer.json
  src/ProxyManager/Version.php
  tests/ProxyManagerTest/Generator/Util/IdentifierSuffixerTest.php
  tests/ProxyManagerTest/Generator/Util/UniqueIdentifierGeneratorTest.php
  tests/ProxyManagerTest/Inflector/ClassNameInflectorTest.php
  tests/ProxyManagerTest/Inflector/Util/ParameterEncoderTest.php
Labels: enhancement

#585 Fix #574: initialize typed nullable properties on PHP >=7.4.1
  composer.json
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/BindProxyProperties.php
  src/ProxyManager/ProxyGenerator/LazyLoadingGhost/MethodGenerator/CallInitializer.php
  src/ProxyManager/ProxyGenerator/Util/Properties.php
  src/ProxyManager/ProxyGenerator/Util/UnsetPropertiesGenerator.php
  tests/ProxyManagerTest/Functional/AccessInterceptorScopeLocalizerFunctionalTest.php
  tests/ProxyManagerTest/Functional/AccessInterceptorValueHolderFunctionalTest.php
  tests/ProxyManagerTest/Functional/LazyLoadingGhostFunctionalTest.php
  tests/ProxyManagerTest/Functional/LazyLoadingValueHolderFunctionalTest.php
  tests/ProxyManagerTest/Functional/MultipleProxyGenerationTest.php
  tests/ProxyManagerTest/Functional/NullObjectFunctionalTest.php
  tests/ProxyManagerTest/Functional/RemoteObjectFunctionalTest.php
  tests/ProxyManagerTest/ProxyGenerator/LazyLoadingGhost/MethodGenerator/CallInitializerTest.php
  tests/ProxyManagerTest/ProxyGenerator/Util/PropertiesTest.php
  tests/ProxyManagerTest/ProxyGenerator/Util/UnsetPropertiesGeneratorTest.php
  tests/ProxyManagerTestAsset/ClassWithPublicStringNullableNullDefaultTypedProperty.php
  tests/ProxyManagerTestAsset/ClassWithPublicStringNullableTypedProperty.php
  tests/ProxyManagerTestAsset/ClassWithPublicStringTypedProperty.php
Labels: bug

#586 #574 remove support for PHP 7.4.1 and newer
  .travis.yml
  composer.json
Labels: bug

#589 Correct type errors in static analysis
  psalm.xml
  tests/ProxyManagerTest/Functional/NullObjectFunctionalTest.php
Labels: bug

#593 Update Psalm to latest and improve templating
  composer.json
  psalm.xml
  tests/ProxyManagerBench/LazyLoadingGhostPropertyAccessBench.php
  tests/ProxyManagerBench/LazyLoadingValueHolderPropertyAccessBench.php
  tests/ProxyManagerTest/Functional/LazyLoadingValueHolderFunctionalTest.php
Labels: dependencies, enhancement
