Repository Ocramius/ProxyManager, pull requests merged in 2020-12, with the labels that each got.

#636 Remove usage of deprecated method
  tests/ProxyManagerTest/ProxyGenerator/Util/PropertiesTest.php
Labels: enhancement

#640 Upgrade to PHPUnit ^9.4
  composer.json
  composer.lock
  phpunit.xml.dist
Labels: dependencies, enhancement

#651 #642 fix fatal error when accessing a dynamic property of a proxied interface (refactored)
  infection.json.dist
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicGet.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicIsset.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicSet.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicUnset.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicGet.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicIsset.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicSet.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicUnset.php
  src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/MagicGet.php
  src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/MagicIsset.php
  src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/MagicSet.php
  src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/MagicUnset.php
  src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php
  tests/ProxyManagerTest/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicGetTest.php
  tests/ProxyManagerTest/ProxyGenerator/Util/PublicScopeSimulatorTest.php
  tests/language-feature-scripts/lazy-loading-value-holder-denies-interface-property-read.phpt
Labels: bug

#642 Replace fatal error with notice when accessing proxied interface dynamic property
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicGet.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicIsset.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicSet.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicUnset.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicGet.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicIsset.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicSet.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicUnset.php
  src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/MagicGet.php
  src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/MagicIsset.php
  src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/MagicSet.php
  src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/MagicUnset.php
  src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php
  tests/language-feature-scripts/lazy-loading-value-holder-interface-proxy.phpt
Labels: bug, question

#652 #646 #632 #645 only variables should be returned by-ref in generated dynamic property access simulation code
  infection.json.dist
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicGet.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicIsset.php
  src/ProxyManager/ProxyGenerator/AccessInterceptorValueHolder/MethodGenerator/MagicUnset.php
  src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php
  tests/ProxyManagerTest/Functional/PublicScopeSimulatorFunctionalTest.php
  tests/ProxyManagerTest/ProxyGenerator/AccessInterceptorScopeLocalizer/MethodGenerator/MagicUnsetTest.php
  tests/ProxyManagerTest/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/MagicUnsetTest.php
  tests/ProxyManagerTest/ProxyGenerator/Util/PublicScopeSimulatorTest.php
Labels: bug

#648 Rename aliases containing "Zend"
  src/ProxyManager/Generator/ClassGenerator.php
  src/ProxyManager/Generator/MethodGenerator.php
  src/ProxyManager/ProxyGenerator/LazyLoadingGhost/MethodGenerator/InitializeProxy.php
Labels: enhancement

#658 Allow (and test) PHP 8.0 type compatibility
  .github/workflows/benchmarks.yml
  .github/workflows/demo-scripts.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/xulieta.yml
  composer.json
  composer.lock
  src/ProxyManager/Factory/AbstractBaseFactory.php
  src/ProxyManager/Generator/ClassGenerator.php
  src/ProxyManager/Generator/Util/ProxiedMethodReturnExpression.php
  src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php
  src/ProxyManager/GeneratorStrategy/FileWriterGeneratorStrategy.php
  tests/ProxyManagerBench/LazyLoadingGhostInstantiationBench.php
  tests/ProxyManagerBench/LazyLoadingValueHolderInstantiationBench.php
  tests/ProxyManagerBench/LazyLoadingValueHolderPropertyAccessBench.php
  tests/ProxyManagerTest/Factory/AccessInterceptorScopeLocalizerFactoryTest.php
  tests/ProxyManagerTest/Factory/AccessInterceptorValueHolderFactoryTest.php
  tests/ProxyManagerTest/Factory/LazyLoadingGhostFactoryTest.php
  tests/ProxyManagerTest/Factory/LazyLoadingValueHolderFactoryTest.php
  tests/ProxyManagerTest/Factory/NullObjectFactoryTest.php
  tests/ProxyManagerTest/Factory/RemoteObjectFactoryTest.php
  tests/ProxyManagerTest/Functional/FatalPreventionFunctionalTest.php
  tests/ProxyManagerTest/Functional/MultipleProxyGenerationTest.php
  tests/ProxyManagerTest/Generator/ClassGeneratorTest.php
  tests/ProxyManagerTest/GeneratorStrategy/BaseGeneratorStrategyTest.php
  tests/ProxyManagerTest/GeneratorStrategy/EvaluatingGeneratorStrategyTest.php
  tests/ProxyManagerTest/GeneratorStrategy/FileWriterGeneratorStrategyTest.php
  tests/ProxyManagerTest/ProxyGenerator/AbstractProxyGeneratorTest.php
  tests/ProxyManagerTest/ProxyGenerator/NullObjectGeneratorTest.php
  tests/ProxyManagerTest/ProxyGenerator/RemoteObjectGeneratorTest.php
  tests/ProxyManagerTestAsset/ClassWithPhp80TypedMethods.php
Labels: dependencies, enhancement
