Repository Ocramius/ProxyManager, pull requests merged in 2020-01, with the labels that each got.

#547 Fixs a few small issues that newest Psalm flagged
  tests/ProxyManagerBench/LazyLoadingValueHolderPropertyAccessBench.php
  tests/ProxyManagerTest/Functional/MultipleProxyGenerationTest.php
Labels: bug

#550 Change missed occurences of zendframework
  docs/remote-object.md
  examples/remote-proxy.php
  psalm.xml
Labels: dependencies, enhancement

#540 RemoteObjectMethod generation: support for methods with default parameters
  composer.json
  src/ProxyManager/ProxyGenerator/RemoteObject/MethodGenerator/RemoteObjectMethod.php
  tests/ProxyManagerTest/Functional/RemoteObjectFunctionalTest.php
  tests/ProxyManagerTest/ProxyGenerator/RemoteObject/MethodGenerator/RemoteObjectMethodTest.php
  tests/ProxyManagerTestAsset/RemoteProxy/RemoteServiceWithDefaultsAndVariadicArguments.php
  tests/ProxyManagerTestAsset/RemoteProxy/RemoteServiceWithDefaultsInterface.php
  tests/Stubbed/Zend/Server/Client.php
  tests/language-feature-scripts/remote-object-json-adapter-default-parameters-and-variadic.phpt
  tests/language-feature-scripts/remote-object-json-adapter-passes-default-parameters-correctly.phpt
Labels: bug

#552 Merge `2.5.x` into `master`, end `2.5.x` support in favour of `2.6.x`
  .travis.yml
  composer.json
  phpcs.xml.dist
  src/ProxyManager/ProxyGenerator/RemoteObject/MethodGenerator/RemoteObjectMethod.php
  tests/ProxyManagerTest/Functional/RemoteObjectFunctionalTest.php
  tests/ProxyManagerTest/ProxyGenerator/RemoteObject/MethodGenerator/RemoteObjectMethodTest.php
  tests/ProxyManagerTestAsset/RemoteProxy/RemoteServiceWithDefaultsAndVariadicArguments.php
  tests/ProxyManagerTestAsset/RemoteProxy/RemoteServiceWithDefaultsInterface.php
  tests/Stubbed/Laminas/Server/Client.php
  tests/language-feature-scripts/remote-object-json-adapter-default-parameters-and-variadic.phpt
  tests/language-feature-scripts/remote-object-json-adapter-passes-default-parameters-correctly.phpt
Labels: bug

#502 Documented basic immutable/mutation-free interfaces and services in the package
  src/ProxyManager/Exception/DisabledMethodException.php
  src/ProxyManager/Exception/ExceptionInterface.php
  src/ProxyManager/Exception/FileNotWritableException.php
  src/ProxyManager/Exception/InvalidProxiedClassException.php
  src/ProxyManager/Exception/InvalidProxyDirectoryException.php
  src/ProxyManager/Exception/UnsupportedProxiedClassException.php
  src/ProxyManager/FileLocator/FileLocator.php
  src/ProxyManager/Generator/ClassGenerator.php
  src/ProxyManager/Generator/MagicMethodGenerator.php
  src/ProxyManager/Generator/MethodGenerator.php
  src/ProxyManager/Generator/Util/IdentifierSuffixer.php
  src/ProxyManager/Generator/Util/ProxiedMethodReturnExpression.php
  src/ProxyManager/Generator/Util/UniqueIdentifierGenerator.php
  src/ProxyManager/Inflector/ClassNameInflector.php
  src/ProxyManager/Inflector/ClassNameInflectorInterface.php
  src/ProxyManager/Inflector/Util/ParameterEncoder.php
  src/ProxyManager/Inflector/Util/ParameterHasher.php
  src/ProxyManager/Proxy/Exception/RemoteObjectException.php
  src/ProxyManager/ProxyGenerator/Assertion/CanProxyAssertion.php
  src/ProxyManager/ProxyGenerator/Util/GetMethodIfExists.php
  src/ProxyManager/ProxyGenerator/Util/Properties.php
  src/ProxyManager/ProxyGenerator/Util/ProxiedMethodsFilter.php
  src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php
  src/ProxyManager/ProxyGenerator/Util/UnsetPropertiesGenerator.php
  src/ProxyManager/Signature/Exception/ExceptionInterface.php
  src/ProxyManager/Signature/Exception/InvalidSignatureException.php
  src/ProxyManager/Signature/Exception/MissingSignatureException.php
  src/ProxyManager/Signature/SignatureChecker.php
  src/ProxyManager/Signature/SignatureCheckerInterface.php
  src/ProxyManager/Signature/SignatureGenerator.php
  src/ProxyManager/Signature/SignatureGeneratorInterface.php
  src/ProxyManager/Stub/EmptyClassStub.php
  src/ProxyManager/Version.php
Labels: enhancement

#553 Revert "Documented basic immutable/mutation-free interfaces and services in the package"
  src/ProxyManager/Exception/DisabledMethodException.php
  src/ProxyManager/Exception/ExceptionInterface.php
  src/ProxyManager/Exception/FileNotWritableException.php
  src/ProxyManager/Exception/InvalidProxiedClassException.php
  src/ProxyManager/Exception/InvalidProxyDirectoryException.php
  src/ProxyManager/Exception/UnsupportedProxiedClassException.php
  src/ProxyManager/FileLocator/FileLocator.php
  src/ProxyManager/Generator/ClassGenerator.php
  src/ProxyManager/Generator/MagicMethodGenerator.php
  src/ProxyManager/Generator/MethodGenerator.php
  src/ProxyManager/Generator/Util/IdentifierSuffixer.php
  src/ProxyManager/Generator/Util/ProxiedMethodReturnExpression.php
  src/ProxyManager/Generator/Util/UniqueIdentifierGenerator.php
  src/ProxyManager/Inflector/ClassNameInflector.php
  src/ProxyManager/Inflector/ClassNameInflectorInterface.php
  src/ProxyManager/Inflector/Util/ParameterEncoder.php
  src/ProxyManager/Inflector/Util/ParameterHasher.php
  src/ProxyManager/Proxy/Exception/RemoteObjectException.php
  src/ProxyManager/ProxyGenerator/Assertion/CanProxyAssertion.php
  src/ProxyManager/ProxyGenerator/Util/GetMethodIfExists.php
  src/ProxyManager/ProxyGenerator/Util/Properties.php
  src/ProxyManager/ProxyGenerator/Util/ProxiedMethodsFilter.php
  src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php
  src/ProxyManager/ProxyGenerator/Util/UnsetPropertiesGenerator.php
  src/ProxyManager/Signature/Exception/ExceptionInterface.php
  src/ProxyManager/Signature/Exception/InvalidSignatureException.php
  src/ProxyManager/Signature/Exception/MissingSignatureException.php
  src/ProxyManager/Signature/SignatureChecker.php
  src/ProxyManager/Signature/SignatureCheckerInterface.php
  src/ProxyManager/Signature/SignatureGenerator.php
  src/ProxyManager/Signature/SignatureGeneratorInterface.php
  src/ProxyManager/Stub/EmptyClassStub.php
  src/ProxyManager/Version.php
Labels: bug

#557 Fix property initializers in ghost object examples
  examples/ghost-object-skipped-properties.php
  examples/ghost-object.php
Labels: bug, docs

#558 Added stream wrapper support to FileLocator
  composer.json
  src/ProxyManager/FileLocator/FileLocator.php
  tests/ProxyManagerTest/FileLocator/FileLocatorTest.php
Labels: bug
